#!/bin/bash
gcc test_LoraWanPkt.c ../libraries/AES-128_V10.c ../libraries/Base64.c ../libraries/LoraWanPkt.c -o test_LoraWanPkt
gcc test_gw.c ../libraries/AES-128_V10.c ../libraries/Base64.c ../libraries/LoraWanPkt.c -o test_gw

